version: "3.8"

services:
  balancer:
    build: ./balancer
    container_name: balancer
    ports:
      - "5000:5000"
    networks:
      - net1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  server:
    build: ./server
    image: myserver:latest
    networks:
      - net1
    expose:
      - "5000"

networks:
  net1:
    name: net1
    driver: bridge

